### ISSUE TITLE
Zonas para visit

### ISSUE THREAD

**Issue by olvap** [bluelemons/muebleria#8]
Necesitamos un metodo en visits que devuelva una coleccion de zonas
las zonas las toma de cada cliente

Client belongs_to :zona
Visit belongs_to :client
Visit#zone mediante delegate, devuelve la zona del cliente
Turns has_many :visits
Turns#zones devuelve todas las zonas de visit sin repetir.

**Comment by eloyesp** [comment]
Por lo que entiendo el método estaría en Turn y serviría para mostrar los labels correspondientes al mostrar dichos turnos.

**Comment by olvap** [comment]
si. ya lo está haciendo el fede.
